### Add Rancher Extensions Chart Repo
apiVersion: catalog.cattle.io/v1
kind: ClusterRepo
metadata:
  name: rancher-ui-plugins
spec:
  gitBranch: main
  gitRepo: https://github.com/rancher/ui-plugin-charts
---
### Add Rancher Government Carbide Chart Repo
apiVersion: catalog.cattle.io/v1
kind: ClusterRepo
metadata:
  name: carbide-charts
spec:
  gitBranch: main
  gitRepo: https://github.com/rancherfederal/carbide-charts
---
apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: ui-plugins
  namespace: fleet-local
spec:
  repo: https://github.com/zackbradys/rgs-carbide
  branch: main
  paths:
    - /fleet/carbide/ui-plugin-operator
---
apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: ui-plugin-crd
  namespace: fleet-local
spec:
  repo: https://github.com/zackbradys/rgs-carbide
  branch: main
  paths:
    - /fleet/carbide/ui-plugin-operator-crd
---
apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: benchmark-crd
  namespace: fleet-local
spec:
  repo: https://github.com/zackbradys/rgs-carbide
  branch: main
  paths:
    - /fleet/carbide/rancher-cis-benchmark-crd
---
apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: benchmark
  namespace: fleet-local
spec:
  repo: https://github.com/zackbradys/rgs-carbide
  branch: main
  paths:
    - /fleet/carbide/rancher-cis-benchmark
---
apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: airgapped-docs
  namespace: fleet-local
spec:
  repo: https://github.com/zackbradys/rgs-carbide
  branch: main
  paths:
    - /fleet/carbide/airgapped-docs
---
apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: stigatron-ui
  namespace: fleet-local
spec:
  repo: https://github.com/zackbradys/rgs-carbide
  branch: main
  paths:
    - /fleet/carbide/stigatron-ui
---
apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: stigatron
  namespace: fleet-local
spec:
  repo: https://github.com/zackbradys/rgs-carbide
  branch: main
  paths:
    - /fleet/carbide/stigatron
---
#apiVersion: fleet.cattle.io/v1alpha1
#kind: GitRepo
#metadata:
#  name: rancher
#  namespace: fleet-local
#spec:
#  repo: https://github.com/zackbradys/rgs-carbide
#  branch: main
#  paths:
#    - /fleet/carbide/rancher