### Add Rancher Government Carbide Chart Repo
apiVersion: catalog.cattle.io/v1
kind: ClusterRepo
metadata:
  name: carbide-charts
spec:
  gitBranch: main
  gitRepo: https://github.com/rancherfederal/carbide-charts
---
apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: monitoring-crd
  namespace: fleet-default
spec:
  repo: https://github.com/zackbradys/rgs-carbide
  branch: main
  paths:
    - /fleet/carbide/rancher-monitoring-crd
  targets:
    - name: downstream-clusters
    - clusterSelector: {}
---
apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: monitoring
  namespace: fleet-default
spec:
  repo: https://github.com/zackbradys/rgs-carbide
  branch: main
  paths:
    - /fleet/carbide/rancher-monitoring
  targets:
    - name: downstream-clusters
    - clusterSelector: {}
---
apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: benchmark-crd
  namespace: fleet-default
spec:
  repo: https://github.com/zackbradys/rgs-carbide
  branch: main
  paths:
    - /fleet/carbide/rancher-cis-benchmark-crd
  targets:
    - name: downstream-clusters
    - clusterSelector: {}
---
apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: benchmark
  namespace: fleet-default
spec:
  repo: https://github.com/zackbradys/rgs-carbide
  branch: main
  paths:
    - /fleet/carbide/rancher-cis-benchmark
  targets:
    - name: downstream-clusters
    - clusterSelector: {}
---
apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: stigatron
  namespace: fleet-default
spec:
  repo: https://github.com/zackbradys/rgs-carbide
  branch: main
  paths:
    - /fleet/carbide/stigatron
  targets:
    - name: downstream-clusters
    - clusterSelector: {}