global:
  cattle:
    systemDefaultRegistry: registry.ranchercarbide.dev
heimdall2:
  global:
    cattle:
      systemDefaultRegistry: registry.ranchercarbide.dev
  heimdall:
    rcidf:
      registry: registry.ranchercarbide.dev
nats:
  global:
    image:
      registry: docker.io
